### ISSUE TITLE
resolver在某些情况下会导致polaris后台卡住

### ISSUE THREAD

**Issue by tsingsun** [polarismesh/grpc-go-polaris#29]
**Describe the bug**

我参考polaris-go-grpc中的实现,在我的库项目[woocoo](https://github.com/tsingsun/woocoo)集成了polaris支持,但在测试过程中发现经常发生的问题.测试方法在[测试方法](https://github.com/tsingsun/woocoo/blob/e1634953091abc79ac96bb342534d8b5dbf26ee2/contrib/polarismesh/client_test.go#L82)

**To Reproduce**

此测试方法主要: 1个服务的2个实例,1个客户端.通过实例的中断测试客户端访问是否正常.

- 自身客户端卡住的同时也导致Polaris后台的服务界面查询卡住..中断测试时后台也恢复正常.
   推测是 在grpc server 关闭时,会执行unregister.此时会导致resolver ResolveNow 高频率的执行.可能导致大量的访问. 
   这在以下位置使用time.sleep时出现.
```
[154		//time.Sleep(time.Second)](https://github.com/tsingsun/woocoo/blob/497566d6086e1dc2cb75b0afebc90c3419fc3638/contrib/polarismesh/client_test.go#L154)
```

建议是避免使用resolver.ResolverNow方法.

** 环境**
MacOS; docker desktop k8s; polaris k8s 部署

**Comment by MIBc** [comment]
ResolverNow是grpc框架控制的，用例无法复现。

**Comment by tsingsun** [comment]
后面的版本我已经改为resolverNow空实现,所以如果你用最新版本的测试用例的话是正常的.
使用当时这个版本的 https://github.com/tsingsun/woocoo/tree/e1634953091abc79ac96bb342534d8b5dbf26ee2

 ResolveNow当时是这样的
```
// ResolveNow The method is called by the gRPC framework to resolve the target name
func (pr *polarisNamingResolver) ResolveNow(opt resolver.ResolveNowOptions) { // 立即resolve，重新查询服务信息
	select {
	case pr.rn <- struct{}{}:
	default:
	}
}
```

**Comment by andrewshan** [comment]
我们解决一下这个问题，不要每次都创建一个api对象
