### ISSUE TITLE
希望配置自定义，而不是依赖配置文件

### ISSUE THREAD

**Issue by JellyZero** [polarismesh/grpc-go-polaris#40]
希望支持 options 这种方式传参，sdk 不应该依赖配置文件和外部文件，希望把服务注册 和配置 中心变成插件化，可插拔，自己实现接口实现替换北极星部分功能，类似 go-micro 插件机制，把北极星当成控制平面使用

**Comment by chuntaojun** [comment]
服务注册 和配置 中心变成插件化
-------
