### ISSUE TITLE
polaris-go 有v2版本了， gRPC-Go with Polaris 没有同步更新gRPC-Go with Polaris

### ISSUE THREAD

**Issue by Owen-Zhang** [polarismesh/grpc-go-polaris#43]
polaris-go 有v2版本了， gRPC-Go with Polaris 没有同步更新gRPC-Go with Polaris

**Comment by houseme** [comment]
没有v2版本，还是这个包名`github.com/polarismesh/polaris-go`

https://github.com/polarismesh/polaris-go/blob/main/go.mod
