### ISSUE TITLE
对接 v2 版的北极星服务报错

### ISSUE THREAD

**Issue by sammyne** [polarismesh/grpc-go-polaris#56]
**Describe the bug**

无法对接 v2 版的北极星服务

**To Reproduce**
使用 sdk 连接 v2 版的北极星系统。

**Expected behavior**

业务能够成功返回响应。

**Got**
错误如下
```bash
rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
```

**Environment**
- Version: [v1.4.0](https://github.com/polarismesh/grpc-go-polaris/tree/v1.4.0)
- OS: Debian 11

**Additional context**

**Comment by chuntaojun** [comment]
这个 v2 版本的北极星是啥版本？
